analytics: "G-VCVX2DGPPN"
domain: "www.calitp.org"
description: "A state government initiative, Cal-ITP is making riding by rail and bus simpler and more cost-effectiveâ€”for California transit providers and riders."
google_fonts: "https://fonts.googleapis.com/css2?family=Poppins:wght@500;700&family=Raleway:wght@900&display=swap"
source: ./src
theme_background_color: "#b82d28"
theme_color: "#b82d28"
title: "Cal-ITP: California Integrated Travel Project"
url: "https://www.calitp.org"
