analytics: "G-VCVX2DGPPN"
collections:
  press:
    output: true
    permalink: /:collection/:name
  resources:
    output: true
    permalink: /:collection/:name
defaults:
  - scope:
      path: ""
      type: press
    values:
      layout: press
  - scope:
      path: ""
      type: resources
    values:
      layout: resource
description: A state government initiative, Cal-ITP is making riding by rail and bus simpler and more cost-effectiveâ€”for California transit providers and riders.
domain: www.calitp.org
google_fonts: "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&family=Raleway:wght@700&display=swap"
navigation:
  header:
    - name: Resources
      url: /resources
    - name: Press
      url: /press
    - name: Reach out
      url: mailto:hello@calitp.org
source: ./src
timezone: America/Los_Angeles
title: "Cal-ITP: California Integrated Travel Project"
url: "https://www.calitp.org"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
