name: calitp-dot-org

services:
  site:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: calitp-dot-org:site
    command: sleep infinity
    volumes:
      - ..:/usr/src/calitp

  docs:
    image: calitp-dot-org:site
    entrypoint: mkdocs
    command: serve --dev-addr "0.0.0.0:8001"
    ports:
      - "8001:8001"
    volumes:
      - ../:/usr/src/calitp
